sudo: required
language: java
dist: trusty
services:
  - docker
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - oraclejdk8
  - oraclejdk9
before_install:
  - export TZ=Asia/Shanghai
script:
  - docker-compose up -d
  - mvn clean verify -Dmaven.skip.integration=false



