sudo: required
language: java
dist: trusty
services:
  - docker
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - oraclejdk8
  - oraclejdk9
script:
  - mvn clean package -DskipTests=true
  - mvn clean verify



