name: gh-pages

on:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: 'npm install'
      - run: 'npm run docs:build'
      - run: 'dev/deploy_gh_pages.sh'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
