name: integration-test

on:
  push:
    branches:
      - "master"
  pull_request_target:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11' ]
        scala: [ '2.11', '2.12' ]
        spark: [ '2.4', '3.0' ]
        exclude:
          - java: '11'
            spark: '2.4'
          - scala: '2.11'
            spark: '3.0'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run integration tests with Scala ${{ matrix.scala }} & Spark ${{ matrix.spark }}
        run: mvn -B clean verify -Pscala-${{ matrix.scala }} -Pspark-${{ matrix.spark }}
      - name: upload code coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.java == '8' && matrix.scala == '2.12' && matrix.spark == '3.0'
        run: bash <(curl -s https://codecov.io/bash)
